### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fant0me**

### CODE REVIEW

**Comment by epageperron** [comment]
Do you have rights to merge? If yes please dont do a PR, just go ahead and merge.

**Comment by NishealJ** [comment]
@epageperron @fant0me(Divya) is learning to create a pull request.
Can you give her access? and me too?

**Comment by epageperron** [comment]
Hi ! For some reason i thought this was you since you were working on this! I'll give you both access in the next minutes.

**Comment by NishealJ** [comment]
> Hi ! For some reason i thought this was you since you were working on this! I'll give you both access in the next minutes.

:D I've received the access

**Pull request merged**
